import { useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { AlertTriangle, ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronRight, Clock3, Flag, Lightbulb, MessageSquareWarning, Sparkles, Star, XCircle } from 'lucide-react'
import { Badge, Button, Card, Progress } from '../components/ui'
import { questions } from '../data/demo'

export default function Assessment() {
  const { id } = useParams()
  const navigate = useNavigate()
  const setQuestions = useMemo(() => id?.startsWith('q') ? [questions.find(q => q.id === id) || questions[0]] : questions, [id])
  const [index, setIndex] = useState(0)
  const [answers, setAnswers] = useState({})
  const [submitted, setSubmitted] = useState(false)
  const [rating, setRating] = useState(null)
  const [challenge, setChallenge] = useState(false)
  const q = setQuestions[index]
  const answer = answers[q.id]
  const isCorrect = q.options ? Number(answer) === q.correct : String(answer || '').trim().replace(/[^\d.-]/g, '') === q.answer
  const earned = isCorrect ? q.marks : 0
  const choose = value => !submitted && setAnswers({ ...answers, [q.id]: value })
  const next = () => { if (index < setQuestions.length - 1) { setIndex(index + 1); setSubmitted(false); setRating(null); setChallenge(false) } else navigate('/progress') }

  return <div className="page-enter mx-auto max-w-5xl">
    <div className="flex items-center justify-between gap-4"><button onClick={() => navigate('/practice')} className="flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-ink"><ArrowLeft size={18}/>Leave practice</button><div className="flex items-center gap-3"><Badge tone="gray"><Clock3 size={13} className="mr-1"/>14:32</Badge><button className="rounded-xl p-2 text-slate-400 hover:bg-white"><Flag size={18}/></button></div></div>
    <div className="mt-6 flex items-center gap-4"><span className="text-xs font-bold text-slate-400">QUESTION {index + 1} OF {setQuestions.length}</span><Progress value={((index + 1) / setQuestions.length) * 100} className="flex-1"/><span className="text-xs font-bold text-leaf-700">{Math.round(((index + 1) / setQuestions.length) * 100)}%</span></div>

    <Card className="mt-6 overflow-hidden">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-black/[.06] bg-slate-50/60 px-6 py-4 sm:px-9"><div className="flex items-center gap-2"><Badge tone={q.subject === 'Science' ? 'blue' : 'green'}>{q.subject}</Badge><span className="text-xs font-bold text-slate-400">{q.topic} · {q.subtopic}</span></div><div className="flex items-center gap-3"><Badge tone={q.difficulty === 'Hard' ? 'red' : q.difficulty === 'Medium' ? 'yellow' : 'green'}>{q.difficulty}</Badge><span className="text-sm font-extrabold">{q.marks} marks</span></div></div>
      <div className="p-6 sm:p-10"><p className="text-sm font-bold text-slate-400">{q.year} O/L Past Paper</p><h2 className="mt-3 font-display text-xl font-bold leading-relaxed sm:text-2xl">{q.text}</h2>
        {q.options ? <div className="mt-8 grid gap-3">{q.options.map((option, i) => { const selected = Number(answer) === i; const correctAfter = submitted && i === q.correct; const wrongAfter = submitted && selected && i !== q.correct; return <button key={option} onClick={() => choose(i)} className={`flex items-center gap-4 rounded-2xl border-2 p-4 text-left transition-all ${correctAfter ? 'border-leaf-500 bg-leaf-50' : wrongAfter ? 'border-red-400 bg-red-50' : selected ? 'border-leaf-500 bg-leaf-50/50' : 'border-black/[.07] hover:border-leaf-300 hover:bg-leaf-50/30'}`}><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl font-display text-sm font-extrabold ${correctAfter ? 'bg-leaf-600 text-white' : wrongAfter ? 'bg-red-500 text-white' : selected ? 'bg-leaf-600 text-white' : 'bg-slate-100 text-slate-500'}`}>{correctAfter ? <Check size={18}/> : wrongAfter ? <XCircle size={18}/> : String.fromCharCode(65 + i)}</span><span className="font-semibold">{option}</span></button>})}</div> : <div className="mt-8"><label className="mb-2 block text-sm font-bold">Your answer</label><div className="relative"><input value={answer || ''} disabled={submitted} onChange={e => choose(e.target.value)} placeholder="Type your answer here" className={`h-14 w-full rounded-2xl border-2 bg-white px-5 text-lg font-semibold outline-none ${submitted ? isCorrect ? 'border-leaf-500 bg-leaf-50' : 'border-red-400 bg-red-50' : 'border-black/[.08] focus:border-leaf-500'}`}/><span className="absolute right-4 top-1/2 -translate-y-1/2 text-sm text-slate-400">Include units if needed</span></div></div>}
      </div>
      {!submitted ? <div className="flex items-center justify-between border-t border-black/[.06] bg-slate-50/60 px-6 py-5 sm:px-9"><button className="flex items-center gap-2 text-sm font-bold text-slate-400 hover:text-amber-600"><Lightbulb size={18}/>I need a hint</button><Button disabled={answer === undefined || answer === ''} onClick={() => setSubmitted(true)}>Check answer <ArrowRight size={17}/></Button></div> : <div className={`border-t p-6 sm:p-9 ${isCorrect ? 'border-leaf-200 bg-leaf-50/60' : 'border-red-200 bg-red-50/40'}`}><div className="flex items-start gap-4"><div className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl text-white ${isCorrect ? 'bg-leaf-600' : 'bg-coral'}`}>{isCorrect ? <CheckCircle2/> : <AlertTriangle/>}</div><div className="flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-display text-xl font-extrabold">{isCorrect ? 'Spot on!' : 'Not quite — keep going.'}</h3><p className="mt-1 text-sm font-bold text-slate-500">You earned {earned} of {q.marks} marks · +{isCorrect ? q.marks * 15 : 5} XP</p></div><Badge tone={isCorrect ? 'green' : 'red'}>{earned}/{q.marks} MARKS</Badge></div><p className="mt-4 rounded-2xl bg-white/70 p-4 text-sm leading-6 text-slate-600"><strong className="text-ink">Why:</strong> {q.explanation}</p><div className="mt-5 flex flex-col justify-between gap-4 border-t border-black/[.06] pt-5 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Was this AI grading helpful?</p><div className="mt-2 flex gap-1">{[1,2,3,4].map(n => <button key={n} onClick={() => setRating(n)} className={`rounded-lg p-1.5 ${rating >= n ? 'text-amber-500' : 'text-slate-300 hover:text-amber-400'}`}><Star size={19} fill={rating >= n ? 'currentColor' : 'none'}/></button>)}</div></div><div className="flex gap-2"><Button variant="ghost" size="sm" onClick={() => setChallenge(!challenge)}><MessageSquareWarning size={16}/>Challenge grade</Button><Button onClick={next}>{index === setQuestions.length - 1 ? 'See progress' : 'Next question'}<ChevronRight size={17}/></Button></div></div>{challenge && <div className="mt-4 rounded-2xl border border-amber-200 bg-white p-4"><label className="text-sm font-bold">Tell us what the grader missed</label><textarea className="mt-2 min-h-24 w-full resize-none rounded-xl border border-black/10 p-3 text-sm outline-none focus:border-leaf-500" placeholder="Explain why you think this grade should be reviewed…"/><div className="mt-3 flex justify-end"><Button size="sm" onClick={() => setChallenge(false)}>Submit challenge</Button></div><p className="mt-2 text-xs text-slate-400">Corrections update your personal metrics only, never global rankings.</p></div>}</div></div></div>}
    </Card>
  </div>
}
