import { useState } from 'react'
import { Award, Crown, Eye, EyeOff, Info, Medal, ShieldCheck, Sparkles, Trophy } from 'lucide-react'
import { Avatar, Badge, Button, Card, Select } from '../components/ui'
import { leaders } from '../data/demo'

export default function Leaderboard() {
  const [visible, setVisible] = useState(true)
  const [metric, setMetric] = useState('Weekly XP')
  const podium = leaders.slice(0, 3)
  return <div className="page-enter"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Badge tone="purple"><Trophy size={12} className="mr-1"/> GLOBAL LEADERBOARD</Badge><h2 className="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl">Rise together.</h2><p className="mt-2 text-slate-500">A little friendly competition, with privacy always in your hands.</p></div><div className="flex gap-2"><Select value={metric} onChange={e => setMetric(e.target.value)}><option>Weekly XP</option><option>Total points</option><option>Topic mastery</option><option>Exam coverage</option></Select><Button variant="secondary" onClick={() => setVisible(!visible)}>{visible ? <Eye size={16}/> : <EyeOff size={16}/>}{visible ? 'You’re visible' : 'You’re hidden'}</Button></div></div>
    {!visible && <div className="mt-6 flex items-start gap-3 rounded-2xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-800"><ShieldCheck className="mt-0.5 shrink-0" size={18}/><div><strong>You’re hidden from public rankings.</strong><p className="mt-1 text-sky-700">You still earn points and can privately see where you would rank. Aggregate statistics remain anonymous.</p></div></div>}
    <Card className="noise relative mt-8 overflow-hidden border-0 bg-ink px-5 pb-0 pt-9 text-white sm:px-10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(47,168,102,.32),transparent_55%)]"/><div className="relative grid min-h-72 grid-cols-3 items-end gap-3 sm:gap-8">{[podium[1], podium[0], podium[2]].map((x, i) => { const first = x.rank === 1; return <div key={x.rank} className="flex flex-col items-center"><div className="relative">{first && <Crown className="absolute -top-8 left-1/2 -translate-x-1/2 text-sun" fill="currentColor"/>}<Avatar initials={x.avatar} className={`${first ? 'h-20 w-20 text-lg ring-sun' : 'h-16 w-16'} bg-white text-ink ring-4 ring-white/15`}/><span className={`absolute -bottom-2 left-1/2 grid h-7 w-7 -translate-x-1/2 place-items-center rounded-full font-extrabold ${first ? 'bg-sun text-ink' : x.rank === 2 ? 'bg-slate-300 text-ink' : 'bg-orange-400 text-white'}`}>{x.rank}</span></div><p className="mt-5 font-display text-sm font-extrabold sm:text-lg">{x.name}</p><p className="mt-1 text-xs font-bold text-white/50 sm:text-sm">{x.points.toLocaleString()} XP</p><div className={`mt-5 w-full rounded-t-3xl ${first ? 'h-28 bg-leaf-500/40' : 'h-20 bg-white/10'} grid place-items-center`}><Medal className={first ? 'text-sun' : 'text-white/25'} /></div></div>})}</div></Card>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_.32fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-black/[.06] p-6"><div><h3 className="font-display text-xl font-extrabold">This week’s top learners</h3><p className="mt-1 text-sm text-slate-400">Resets every Monday at midnight</p></div><Badge tone="gray">TOP 100</Badge></div><div>{leaders.map(x => <div key={x.rank} className={`flex items-center gap-4 border-b border-black/[.05] px-5 py-4 last:border-0 sm:px-6 ${x.current ? 'bg-leaf-50' : ''}`}><span className={`w-7 text-center font-display text-sm font-extrabold ${x.rank <= 3 ? 'text-amber-600' : 'text-slate-400'}`}>#{x.rank}</span><Avatar initials={x.avatar}/><div className="flex-1"><div className="flex items-center gap-2"><p className="text-sm font-bold">{x.name}</p>{x.current && <Badge>YOU</Badge>}</div><p className="text-xs text-slate-400">O/L learner · Level {x.rank < 4 ? 10 : 7}</p></div><span className={`hidden text-xs font-bold sm:block ${x.change.includes('↑') ? 'text-leaf-600' : x.change.includes('↓') ? 'text-coral' : 'text-slate-300'}`}>{x.change}</span><p className="w-24 text-right font-display text-sm font-extrabold">{x.points.toLocaleString()} XP</p></div>)}</div></Card><div className="space-y-5"><Card className="bg-[#fff8e8] p-6 shadow-none"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-sun/40 text-amber-700"><Award/></div><h3 className="mt-4 font-display text-xl font-extrabold">Your weekly goal</h3><p className="mt-2 text-sm leading-6 text-slate-500">Earn 410 more XP to reach the top 15.</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-amber-100"><div className="h-full w-[68%] rounded-full bg-amber-500"/></div><div className="mt-2 flex justify-between text-xs font-bold text-amber-700"><span>840 XP</span><span>1,250 XP</span></div></Card><Card className="p-6 shadow-none"><div className="flex gap-3"><Info size={18} className="shrink-0 text-sky-500"/><div><h4 className="text-sm font-bold">Fair play matters</h4><p className="mt-1 text-xs leading-5 text-slate-400">Challenged grade corrections improve your personal progress, but never alter global ranking points.</p></div></div></Card></div></div>
  </div>
}
