import { useMemo, useState } from 'react'
import { ArrowRight, BookOpen, CalendarRange, Clock3, FileText, History, PlayCircle, Search, Sparkles } from 'lucide-react'
import { Badge, Button, Card, Progress, Select } from '../components/ui'
import { lessons } from '../data/demo'

const tones = { coral: 'bg-[#fff1ec] text-coral', green: 'bg-leaf-50 text-leaf-600', blue: 'bg-sky-50 text-sky-600', yellow: 'bg-amber-50 text-amber-600' }

export default function Learn() {
  const [subject, setSubject] = useState('All subjects')
  const [search, setSearch] = useState('')
  const filtered = useMemo(() => lessons.filter(x => (subject === 'All subjects' || x.subject === subject) && `${x.title} ${x.topic}`.toLowerCase().includes(search.toLowerCase())), [subject, search])
  return <div className="page-enter"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Badge><BookOpen size={12} className="mr-1"/> LEARNING LIBRARY</Badge><h2 className="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl">Understand it, then own it.</h2><p className="mt-2 text-slate-500">Short lessons and clear notes, mapped to exactly what you practise.</p></div><div className="flex gap-2"><div className="relative"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e => setSearch(e.target.value)} className="h-11 w-48 rounded-2xl border border-black/10 bg-white pl-10 pr-3 text-sm outline-none focus:border-leaf-500" placeholder="Search library"/></div><Select value={subject} onChange={e => setSubject(e.target.value)}><option>All subjects</option><option>Mathematics</option><option>Science</option></Select></div></div>
    <Card className="noise relative mt-8 overflow-hidden border-0 bg-[#dff3d6] p-7 shadow-none sm:p-9"><div className="absolute bottom-0 right-0 h-48 w-64 rounded-tl-full bg-leaf-500/10"/><div className="relative max-w-2xl"><Badge className="bg-white/70"><Sparkles size={12} className="mr-1"/> CONTINUE LEARNING</Badge><h3 className="mt-4 font-display text-2xl font-extrabold sm:text-3xl">Series and parallel circuits</h3><p className="mt-2 text-sm leading-6 text-slate-600">You’re 35% through this lesson. Next up: how current divides at a junction.</p><Progress value={35} className="mt-5 max-w-md bg-white/70"/><div className="mt-5 flex items-center gap-4"><Button><PlayCircle size={17}/>Continue lesson</Button><span className="flex items-center gap-1 text-sm font-semibold text-slate-500"><Clock3 size={15}/>8 min left</span></div></div></Card>
    <div className="mt-8 flex items-center justify-between"><div><h3 className="font-display text-xl font-extrabold">Recommended for you</h3><p className="mt-1 text-sm text-slate-400">Chosen from your practice history</p></div><button className="text-sm font-bold text-leaf-700">View all</button></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{filtered.map(x => <Card key={x.id} className="group overflow-hidden shadow-none transition-all hover:-translate-y-1 hover:shadow-soft"><div className={`relative grid h-36 place-items-center ${tones[x.tone]}`}><span className="text-5xl">{x.subject === 'Science' ? x.topic === 'Electricity' ? '⚡' : '📈' : x.topic === 'Algebra' ? '𝑥²' : '◯'}</span><Badge className="absolute left-4 top-4 bg-white/80" tone={x.type === 'Note' ? 'purple' : 'green'}>{x.type}</Badge></div><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{x.subject} · {x.topic}</p><h4 className="mt-2 font-display text-lg font-extrabold leading-snug">{x.title}</h4><p className="mt-2 line-clamp-2 text-sm leading-5 text-slate-500">{x.description}</p>{x.progress > 0 ? <div className="mt-4"><div className="mb-1 flex justify-between text-[11px] font-bold text-slate-400"><span>PROGRESS</span><span>{x.progress}%</span></div><Progress value={x.progress}/></div> : <div className="mt-4 flex items-center justify-between"><span className="flex items-center gap-1 text-xs font-semibold text-slate-400"><Clock3 size={14}/>{x.duration}</span><ArrowRight size={17} className="text-leaf-600 transition-transform group-hover:translate-x-1"/></div>}</div></Card>)}{filtered.length === 0 && <p className="col-span-full py-12 text-center text-slate-400">No lessons found.</p>}</div>
    <div className="mt-8 grid gap-5 lg:grid-cols-2"><Card className="p-6 shadow-none"><div className="flex items-start gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-50 text-violet-600"><History size={22}/></span><div className="flex-1"><div className="flex items-center justify-between"><div><h3 className="font-display text-lg font-extrabold">Syllabus changes</h3><p className="mt-1 text-sm text-slate-400">Know what changed between exam years.</p></div><ArrowRight size={18} className="text-slate-300"/></div><div className="mt-4 rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-2"><Badge tone="purple">SCIENCE</Badge><span className="text-xs font-bold text-slate-400">2024 UPDATE</span></div><p className="mt-2 text-sm font-bold">Changes to the environmental chemistry unit</p></div></div></div></Card><Card className="p-6 shadow-none"><div className="flex items-start gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-sky-50 text-sky-600"><FileText size={22}/></span><div><h3 className="font-display text-lg font-extrabold">Quick revision notes</h3><p className="mt-1 text-sm text-slate-400">Download-friendly topic summaries for the final review.</p><Button className="mt-4" variant="secondary" size="sm">Browse notes <ArrowRight size={15}/></Button></div></div></Card></div>
  </div>
}
