import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, BookMarked, Check, ChevronRight, Clock3, Filter, RotateCcw, Search, Shuffle, Sparkles, Target, WandSparkles } from 'lucide-react'
import { Badge, Button, Card, Select } from '../components/ui'
import { questions } from '../data/demo'

const topics = ['All topics', 'Algebra', 'Geometry', 'Measurement', 'Electricity', 'Mechanics']

export default function Practice() {
  const navigate = useNavigate()
  const [subject, setSubject] = useState('All subjects')
  const [topic, setTopic] = useState('All topics')
  const [difficulty, setDifficulty] = useState('Any difficulty')
  const [count, setCount] = useState(10)
  const [search, setSearch] = useState('')
  const filtered = useMemo(() => questions.filter(q => (subject === 'All subjects' || q.subject === subject) && (topic === 'All topics' || q.topic === topic) && (difficulty === 'Any difficulty' || q.difficulty === difficulty) && q.text.toLowerCase().includes(search.toLowerCase())), [subject, topic, difficulty, search])

  return <div className="page-enter">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Badge><Target size={12} className="mr-1" /> PRACTICE HUB</Badge><h2 className="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl">What shall we work on?</h2><p className="mt-2 text-slate-500">Build a focused assessment or pick a question from the bank.</p></div><Button variant="secondary" onClick={() => navigate('/assessment/random')}><Shuffle size={17} /> Surprise me</Button></div>

    <div className="mt-8 grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
      <Card className="overflow-hidden border-0 bg-ink text-white">
        <div className="dot-grid relative p-7 sm:p-8"><div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-leaf-500/20 blur-3xl"/><div className="relative"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white/10 text-sun"><WandSparkles size={22}/></span><div><p className="font-display text-xl font-extrabold">Create a practice set</p><p className="text-sm text-white/50">Tailored to your goal</p></div></div><div className="mt-7 space-y-5"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-widest text-white/50">Subject</span><select value={subject} onChange={e => setSubject(e.target.value)} className="h-12 w-full rounded-2xl border border-white/10 bg-white/10 px-4 text-sm font-semibold text-white outline-none"><option className="text-ink">All subjects</option><option className="text-ink">Mathematics</option><option className="text-ink">Science</option></select></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-widest text-white/50">Focus topic</span><select value={topic} onChange={e => setTopic(e.target.value)} className="h-12 w-full rounded-2xl border border-white/10 bg-white/10 px-4 text-sm font-semibold text-white outline-none">{topics.map(x => <option className="text-ink" key={x}>{x}</option>)}</select></label><div><div className="mb-2 flex justify-between text-xs font-bold uppercase tracking-widest text-white/50"><span>Questions</span><span className="text-sun">{count}</span></div><input type="range" min="5" max="25" step="5" value={count} onChange={e => setCount(e.target.value)} className="w-full accent-[#f6c453]"/><div className="mt-1 flex justify-between text-[10px] text-white/30"><span>5</span><span>25</span></div></div><div className="grid grid-cols-2 gap-3"><button className="rounded-2xl border border-white/10 bg-white/5 p-3 text-left hover:bg-white/10"><Clock3 size={17} className="text-sun"/><span className="mt-2 block text-sm font-bold">15 minutes</span><span className="text-xs text-white/40">Time limit</span></button><button className="rounded-2xl border border-leaf-500 bg-leaf-500/10 p-3 text-left"><Sparkles size={17} className="text-[#8de4ac]"/><span className="mt-2 block text-sm font-bold">Smart mix</span><span className="text-xs text-white/40">Difficulty</span></button></div><Button className="w-full bg-white text-ink shadow-none hover:bg-leaf-50" size="lg" onClick={() => navigate('/assessment/custom')}>Build my assessment <ArrowRight size={18}/></Button></div></div></div>
      </Card>

      <div className="space-y-5">
        <Card className="border-amber-200/60 bg-[#fffaf0] p-6 shadow-none"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-amber-100 text-amber-700"><Sparkles size={22}/></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-display text-lg font-extrabold">Weak-topic workout</h3><Badge tone="yellow">Recommended</Badge></div><p className="mt-1 text-sm text-slate-500">6 questions on Electricity and Geometry, selected from recent mistakes.</p></div></div><Button onClick={() => navigate('/assessment/weak-topics')}>Start now <ChevronRight size={16}/></Button></div></Card>

        <Card className="p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h3 className="font-display text-xl font-extrabold">Question bank</h3><p className="mt-1 text-sm text-slate-400">{filtered.length} questions in this demo collection</p></div><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search questions" className="h-10 rounded-2xl border border-black/10 bg-slate-50 pl-9 pr-3 text-sm outline-none focus:border-leaf-500"/></div></div><div className="mt-5 flex flex-wrap gap-2"><Select value={subject} onChange={e => setSubject(e.target.value)} className="h-10"><option>All subjects</option><option>Mathematics</option><option>Science</option></Select><Select value={topic} onChange={e => setTopic(e.target.value)} className="h-10">{topics.map(x => <option key={x}>{x}</option>)}</Select><Select value={difficulty} onChange={e => setDifficulty(e.target.value)} className="h-10"><option>Any difficulty</option><option>Easy</option><option>Medium</option><option>Hard</option></Select><Button variant="ghost" size="sm" onClick={() => { setSubject('All subjects'); setTopic('All topics'); setDifficulty('Any difficulty'); setSearch('') }}><RotateCcw size={15}/>Reset</Button></div><div className="mt-4 divide-y divide-black/[.05]">{filtered.map(q => <button key={q.id} onClick={() => navigate(`/assessment/${q.id}`)} className="group flex w-full items-center gap-4 py-4 text-left"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${q.subject === 'Mathematics' ? 'bg-leaf-50 text-leaf-700' : 'bg-sky-50 text-sky-700'}`}><BookMarked size={19}/></span><span className="min-w-0 flex-1"><span className="mb-1 flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-slate-400">{q.subject} · {q.year}</span><Badge tone={q.difficulty === 'Hard' ? 'red' : q.difficulty === 'Medium' ? 'yellow' : 'green'}>{q.difficulty}</Badge></span><span className="block truncate text-sm font-bold">{q.text}</span></span><span className="hidden text-right sm:block"><span className="block text-sm font-bold">{q.marks} marks</span><span className="text-xs text-slate-400">{q.topic}</span></span><ChevronRight size={18} className="text-slate-300 transition-transform group-hover:translate-x-1 group-hover:text-leaf-600"/></button>)}{filtered.length === 0 && <div className="py-12 text-center"><Filter className="mx-auto text-slate-300"/><p className="mt-3 font-bold">No questions match these filters</p><p className="mt-1 text-sm text-slate-400">Try broadening your selection.</p></div>}</div></Card>
      </div>
    </div>
  </div>
}
