import { useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowUpRight, Award, BookCheck, BrainCircuit, CalendarDays, CheckCircle2, CircleAlert, Clock3, Download, Flame, Target, TrendingUp } from 'lucide-react'
import { Badge, Button, Card, Progress, Select } from '../components/ui'
import { activity, mastery } from '../data/demo'

const longActivity = [...activity, ...activity.map((x, i) => ({ ...x, day: `W2-${i + 1}`, score: x.score + (i % 3) }))]

export default function ProgressPage() {
  const [subject, setSubject] = useState('All subjects')
  return <div className="page-enter">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Badge><TrendingUp size={12} className="mr-1"/> YOUR GROWTH</Badge><h2 className="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl">Progress you can feel.</h2><p className="mt-2 text-slate-500">Every answer tells us where you’re growing and what to practise next.</p></div><div className="flex gap-2"><Select value={subject} onChange={e => setSubject(e.target.value)}><option>All subjects</option><option>Mathematics</option><option>Science</option></Select><Button variant="secondary"><Download size={16}/>Report</Button></div></div>

    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-5 shadow-none"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-leaf-50 text-leaf-600"><Target size={20}/></span><Badge>+6%</Badge></div><p className="mt-5 font-display text-3xl font-extrabold">72%</p><p className="mt-1 text-sm font-semibold text-slate-400">Overall mastery</p></Card><Card className="p-5 shadow-none"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-sky-50 text-sky-600"><BookCheck size={20}/></span><Badge tone="blue">74%</Badge></div><p className="mt-5 font-display text-3xl font-extrabold">148</p><p className="mt-1 text-sm font-semibold text-slate-400">Questions covered</p></Card><Card className="p-5 shadow-none"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-orange-50 text-orange-500"><Flame size={20}/></span><Badge tone="yellow">Personal best</Badge></div><p className="mt-5 font-display text-3xl font-extrabold">12 days</p><p className="mt-1 text-sm font-semibold text-slate-400">Current streak</p></Card><Card className="p-5 shadow-none"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-violet-50 text-violet-600"><Clock3 size={20}/></span><Badge tone="purple">This month</Badge></div><p className="mt-5 font-display text-3xl font-extrabold">8.4 hrs</p><p className="mt-1 text-sm font-semibold text-slate-400">Focused study</p></Card></div>

    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Card className="p-6 sm:p-7"><div className="flex items-start justify-between"><div><h3 className="font-display text-xl font-extrabold">Accuracy trend</h3><p className="mt-1 text-sm text-slate-400">Your rolling score over the last two weeks</p></div><Badge tone="green"><ArrowUpRight size={13} className="mr-1"/>Improving</Badge></div><div className="mt-6 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={longActivity}><defs><linearGradient id="progressArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2fa866" stopOpacity={.3}/><stop offset="100%" stopColor="#2fa866" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef1ee"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fontSize: 10, fill:'#94a3b8'}}/><YAxis domain={[40,100]} axisLine={false} tickLine={false} tick={{fontSize:10, fill:'#94a3b8'}}/><Tooltip contentStyle={{border:0,borderRadius:14,boxShadow:'0 10px 30px #0002'}} formatter={v => [`${v}%`, 'Accuracy']}/><Area type="monotone" dataKey="score" stroke="#2fa866" strokeWidth={3} fill="url(#progressArea)"/></AreaChart></ResponsiveContainer></div></Card><Card className="p-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-red-50 text-coral"><BrainCircuit size={21}/></span><div><h3 className="font-display text-lg font-extrabold">Priority focus</h3><p className="text-xs text-slate-400">Based on repeated mistakes</p></div></div><div className="mt-6 rounded-3xl bg-[#fff4ef] p-5"><div className="flex items-center justify-between"><Badge tone="red">URGENT REVISION</Badge><span className="font-display text-2xl font-extrabold text-coral">42%</span></div><h4 className="mt-4 font-display text-xl font-extrabold">Electricity</h4><p className="mt-2 text-sm leading-6 text-slate-500">Series circuits and electrical power are costing you the most marks.</p><Button className="mt-5 w-full" variant="dark">Start focused practice</Button></div></Card></div>

    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="p-6"><div><h3 className="font-display text-xl font-extrabold">Topic breakdown</h3><p className="mt-1 text-sm text-slate-400">Mastery combines accuracy, consistency and recency.</p></div><div className="mt-5 space-y-5">{mastery.map((x, i) => <div key={x.topic}><div className="mb-2 flex items-center justify-between"><div className="flex items-center gap-3"><span className={`grid h-9 w-9 place-items-center rounded-xl ${i === 3 ? 'bg-red-50 text-red-600' : i === 2 ? 'bg-amber-50 text-amber-600' : 'bg-leaf-50 text-leaf-600'}`}>{i === 3 ? <CircleAlert size={17}/> : <CheckCircle2 size={17}/>}</span><div><p className="text-sm font-bold">{x.topic}</p><p className="text-[11px] text-slate-400">{x.subject}</p></div></div><span className="font-display text-lg font-extrabold">{x.score}%</span></div><Progress value={x.score} indicatorClassName={i === 3 ? 'bg-coral' : i === 2 ? 'bg-amber-500' : 'bg-leaf-500'}/></div>)}</div></Card><Card className="p-6"><div className="flex items-center justify-between"><div><h3 className="font-display text-xl font-extrabold">Recent milestones</h3><p className="mt-1 text-sm text-slate-400">The small wins add up.</p></div><Award className="text-amber-500"/></div><div className="mt-6 space-y-3">{[{icon:'🏅',title:'Algebra Apprentice',note:'Reached 80% mastery in Algebra',date:'Today'},{icon:'🔥',title:'On a roll',note:'Completed a 10-day practice streak',date:'2 days ago'},{icon:'⚡',title:'Quick thinker',note:'Answered 10 questions in under 8 minutes',date:'5 days ago'}].map(x => <div key={x.title} className="flex items-center gap-4 rounded-2xl border border-black/[.05] p-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-amber-50 text-2xl">{x.icon}</span><div className="flex-1"><p className="text-sm font-bold">{x.title}</p><p className="mt-0.5 text-xs text-slate-400">{x.note}</p></div><span className="text-[11px] font-bold text-slate-400">{x.date}</span></div>)}</div></Card></div>
  </div>
}
